version: 2

jobs:
  build:
    working_directory: /members-search-app
    docker:
      - image: makkke/node
    steps:
      - checkout

      - run:
          name: Install Node.js dependencies
          command: yarn install

      - run:
          name: Lint Test
          command: yarn run test:lint

      - run:
          name: Unit Test
          command: yarn run test:unit

      - run:
          name: Build
          command: yarn run build

      # - run:
      #     name: Deploy to production
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         # aws s3 sync ./public s3://app.memberssearch.com/ --delete
      #       fi
